version: "3.7"
services:
  balancer:
    image: nginx
    ports:
      - 80:80/tcp
    depends_on:
      - web
      - tomcat
    volumes:
      - /home/eugene/work/docker/nginx/etc:/etc/nginx
  web:
    build: .
    volumes:
      - /home/eugene/work/docker/web/etc/sites-enabled:/etc/apache2/sites-enabled
      - /home/eugene/work/docker/web/www:/var/www/site
    depends_on:
      - mysql57
  mysql57:
    image: percona:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: 123123
    volumes:
      - /home/eugene/work/docker/mysql/configs/my.cnf:/etc/mysql/conf.d/custom.cnf
      - /home/eugene/work/docker/mysql/mysql:/var/lib/mysql
  tomcat:
    build: ./tomcat
    ports:
      - '8080:8080'
    volumes:
      - ./tomcat:/bitnami/tomcat
    depends_on:
      - mysql57

